define([], function() {
  return {
    "Title": "HelvetySpoExplorerApplicationCustomizer",
    "ErrorFetchSitesFailed": "Failed to fetch sites",
    "ErrorFetchSitesPermissions": "Unable to fetch sites. Please check your permissions and try again.",
    "LoadingSites": "Loading sites...",
    "NoSitesAvailable": "No sites available",
    "NoSitesAvailableDescription": "No SharePoint sites were found. This could mean no matching sites are currently available via search, or there was an issue loading them.",
    "NoSitesAvailableTroubleshooting": "Try refreshing the list, or check with your administrator if you should have access to sites.",
    "NoSitesFound": "No sites found matching",
    "SearchPlaceholder": "Search sites...",
    "SearchDescription": "Search sites by title, description, or URL",
    "RefreshSites": "Refresh sites",
    "SitesYouHaveAccessTo": "Sites available to you",
    "Favorites": "Favorites",
    "FavoritesQuickAccessMenu": "Favorites quick access menu",
    "AddToFavoritesHint": "Add sites to favorites for quick access",
    "OpenSitesPanel": "Open sites panel",
    "OpenSitesPanelDescription": "Opens the Sites panel to browse and search SharePoint sites. Use the split-button menu for quick access to favorite sites.",
    "ClosePanel": "Close sites panel",
    "SitesPanel": "Sites panel",
    "SitesTab": "Sites",
    "SettingsTab": "Settings",
    "ShowFullUrl": "Show Full URL",
    "ShowPartialUrl": "Show Partial URL",
    "ShowDescription": "Show Description",
    "AlwaysOpenNewTab": "Always open in new tab",
    "SiteExplorerSettings": "Site explorer settings",
    "RemoveFromFavorites": "Remove from favorites",
    "AddToFavorites": "Add to favorites",
    "OpenInNewTab": "Open in new tab",
    "SettingsUrlDisplaySection": "URL Display",
    "SettingsUrlDisplayDescription": "Choose how site URLs are displayed in the sites list. Full URL shows the complete address, while Partial URL shows only the path.",
    "SettingsSiteInfoSection": "Site Information",
    "SettingsSiteInfoDescription": "Control which additional information is shown for each site in the list.",
    "SettingsNavigationSection": "Navigation",
    "SettingsNavigationDescription": "Configure how site links behave when clicked.",
    "AboutTab": "About",
    "AboutAppDescription": "Helvety SPO Explorer runs in your current signed-in user context. You only see SharePoint sites you already have access to, so the displayed sites depend on your permissions. The app itself does not grant or elevate access.",
    "AboutContactLabel": "Contact",
    "AboutContactEmail": "contact@helvety.com",
    "AboutLinksLabel": "Links",
    "AboutHelvetyLinkLabel": "Helvety Website",
    "AboutHelvetyLinkUrl": "https://helvety.com",
    "AboutGithubLinkLabel": "Open Source on GitHub",
    "AboutGithubLinkUrl": "https://github.com/CasparRubin/helvety-spo-explorer",
    "AboutNotAvailable": "—",
    "AboutVersion": "Version",
    "AboutBuiltOn": "Built on",
    "ToggleOn": "On",
    "ToggleOff": "Off",
    "AriaSettingsDescription": "Customize display options for the site explorer, including URL visibility and link behavior",
    "AriaAboutRegion": "About Helvety SPO Explorer",
    "AppName": "Helvety SPO Explorer",
    "AriaSiteNavigation": "Site navigation",
    "AriaSitesPanelDescription": "Panel containing tabs for browsing sites, settings, and about",
    "AriaSitesPanelNavigation": "Sites panel navigation"
  }
});