declare interface IHelvetySpoExplorerApplicationCustomizerStrings {
  Title: string;
  ErrorFetchSitesFailed: string;
  ErrorFetchSitesPermissions: string;
  LoadingSites: string;
  NoSitesAvailable: string;
  NoSitesAvailableDescription: string;
  NoSitesAvailableTroubleshooting: string;
  NoSitesFound: string;
  SearchPlaceholder: string;
  SearchDescription: string;
  RefreshSites: string;
  SitesYouHaveAccessTo: string;
  Favorites: string;
  FavoritesQuickAccessMenu: string;
  AddToFavoritesHint: string;
  OpenSitesPanel: string;
  OpenSitesPanelDescription: string;
  ClosePanel: string;
  SitesPanel: string;
  SitesTab: string;
  SettingsTab: string;
  ShowFullUrl: string;
  ShowPartialUrl: string;
  ShowDescription: string;
  AlwaysOpenNewTab: string;
  SiteExplorerSettings: string;
  RemoveFromFavorites: string;
  AddToFavorites: string;
  OpenInNewTab: string;
  SettingsUrlDisplaySection: string;
  SettingsUrlDisplayDescription: string;
  SettingsSiteInfoSection: string;
  SettingsSiteInfoDescription: string;
  SettingsNavigationSection: string;
  SettingsNavigationDescription: string;
  AboutTab: string;
  AboutAppDescription: string;
  AboutContactLabel: string;
  AboutContactEmail: string;
  AboutLinksLabel: string;
  AboutHelvetyLinkLabel: string;
  AboutHelvetyLinkUrl: string;
  AboutGithubLinkLabel: string;
  AboutGithubLinkUrl: string;
  AboutNotAvailable: string;
  AboutVersion: string;
  AboutBuiltOn: string;
  ToggleOn: string;
  ToggleOff: string;
  AriaSettingsDescription: string;
  AriaAboutRegion: string;
  AppName: string;
  AriaSiteNavigation: string;
  AriaSitesPanelDescription: string;
  AriaSitesPanelNavigation: string;
}

declare module "HelvetySpoExplorerApplicationCustomizerStrings" {
  const strings: IHelvetySpoExplorerApplicationCustomizerStrings;
  export = strings;
}
